project_id = "boexvvxampnunufciqrg"

[auth]
enabled = true
# Site URL and redirects are handled by environment variables
additional_redirect_urls = [
  "http://localhost:3000",
  "http://localhost:3000/auth/callback",
  "https://gifters.vercel.app",
  "https://gifters.vercel.app/auth/callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[auth.external.github]
enabled = true
# Client ID and secret are configured via Supabase dashboard
# Redirect URI is handled by environment variables

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = false
