import { Metadata } from "next";

import { generateOrganizationSchema, generateWebsiteSchema } from "../utils/schema";

/**
 * Canonical site identity. Single source of truth for the cross-cutting SEO
 * machinery (root metadata, JSON-LD, robots, sitemap, OG image).
 */
export const SITE = {
  name: "PoE2 Tools",
  url: "https://poe2.dev",
  // 1200x630 OG image generated by src/app/opengraph-image.tsx
  ogImage: "/opengraph-image",
  twitter: "@poe2tools",
  description:
    "A Path of Exile 2 toolkit: interactive skill tree, build planner, DPS and currency calculators, ascendancy and mechanics references, and patch-note tracking.",
} as const;

/**
 * Strong, self-referential default metadata for the whole site.
 *
 * Per-route `page.tsx`/`layout.tsx` files override `title`/`description`/
 * `alternates.canonical` as needed; this provides the sensible default that
 * every route inherits. Consumed by `src/app/layout.tsx`.
 *
 * NOTE: this is async + named `generateMetadata` to preserve the existing
 * import contract in `src/app/layout.tsx` (`export { generateMetadata }`).
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    metadataBase: new URL(SITE.url),
    applicationName: SITE.name,
    title: {
      // Per-route titles render as "Route · PoE2 Tools".
      template: `%s · ${SITE.name}`,
      default: `${SITE.name} · Path of Exile 2 Build Planner, Skill Tree & Calculators`,
    },
    description: SITE.description,
    keywords: [
      "path of exile 2",
      "poe2",
      "poe2 tools",
      "poe2 build planner",
      "poe2 skill tree",
      "poe2 dps calculator",
      "poe2 currency",
      "poe2 ascendancies",
      "poe2 mechanics",
      "poe2 patch notes",
    ],
    authors: [{ name: `${SITE.name} Team` }],
    creator: SITE.name,
    publisher: SITE.name,
    category: "Gaming Tools",
    alternates: {
      // Self-referential canonical for the home document; routes override this.
      canonical: "/",
      types: {
        "application/rss+xml": [{ url: "/feed.xml", title: `${SITE.name} Updates` }],
      },
    },
    icons: {
      icon: [
        { url: "/favicon.ico", sizes: "any" },
        { url: "/favicon.svg", type: "image/svg+xml" },
        { url: "/icon.svg", type: "image/svg+xml" },
      ],
      shortcut: ["/favicon.ico"],
      apple: [{ url: "/icon.svg" }],
    },
    manifest: "/manifest.json",
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: SITE.name,
      url: SITE.url,
      title: `${SITE.name} · Path of Exile 2 Build Planner, Skill Tree & Calculators`,
      description: SITE.description,
      images: [
        {
          url: SITE.ogImage,
          width: 1200,
          height: 630,
          alt: `${SITE.name} — Path of Exile 2 toolkit`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${SITE.name} · Path of Exile 2 Build Planner, Skill Tree & Calculators`,
      description: SITE.description,
      images: [SITE.ogImage],
      creator: SITE.twitter,
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-image-preview": "large",
        "max-snippet": -1,
        "max-video-preview": -1,
      },
    },
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || undefined,
    },
  };
}

/**
 * Site-wide JSON-LD graph (Organization + WebSite). Rendered as a real
 * `<script type="application/ld+json">` in `src/app/layout.tsx` — NOT via
 * `metadata.other`. No SearchAction (the old one pointed at a non-existent
 * search endpoint).
 */
export function getSiteJsonLd() {
  return [generateOrganizationSchema(SITE), generateWebsiteSchema(SITE)];
}
